version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.0
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres

    working_directory: ~/posts/server  
    
    steps:
      - checkout:
          path: ~/posts
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest

workflows:
  build-and-test:
    jobs:
      - build-and-test
