version: 2.1
orbs:
  python: circleci/python@2.1.1
  
jobs:
  build-and-test:
    docker:
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres

      - image: cimg/python:3.11.0

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest

workflows:
  test_app:
    jobs:
      - build-and-test
