"""Remove posts_comments junction table

Revision ID: 46771d436ed7
Revises: 31a1e2ea098c
Create Date: 2023-05-01 19:58:10.709868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46771d436ed7'
down_revision = '31a1e2ea098c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_comments',
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['posts.id'], name='posts_comments_comment_id_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='posts_comments_post_id_fkey'),
    sa.PrimaryKeyConstraint('post_id', 'comment_id', name='posts_comments_pkey')
    )
    # ### end Alembic commands ###
