"""Add waitlist to store a private user's pending subscriber

Revision ID: 7a55ec225dc8
Revises: be66a64c211c
Create Date: 2023-05-10 03:14:43.564829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a55ec225dc8'
down_revision = 'be66a64c211c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_subscribers_waitlist',
    sa.Column('judge', sa.UUID(), nullable=False),
    sa.Column('judged', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['judge'], ['users.id'], ),
    sa.ForeignKeyConstraint(['judged'], ['users.id'], ),
    sa.PrimaryKeyConstraint('judge', 'judged')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_subscribers_waitlist')
    # ### end Alembic commands ###
