"""Create posts_reposts junction table. Create many to many relationship between users and posts table

Revision ID: a1edb20d69e5
Revises: 078e7a7a27ef
Create Date: 2023-05-01 05:11:02.801496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1edb20d69e5'
down_revision = '078e7a7a27ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_reposts',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('reposter_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['reposter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'reposter_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_reposts')
    # ### end Alembic commands ###
