"""Remove following and followers columns

Revision ID: 7b908db6ebf1
Revises: 026c063f6466
Create Date: 2023-04-28 18:54:37.593473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b908db6ebf1'
down_revision = '026c063f6466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('following')
        batch_op.drop_column('followers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followers', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('following', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
