"""Create user network relation

Revision ID: da433662ffc3
Revises: 7b908db6ebf1
Create Date: 2023-04-28 22:45:01.781137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da433662ffc3'
down_revision = '7b908db6ebf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('subscriber_id', sa.UUID(), nullable=True),
    sa.Column('subscribee_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['subscribee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###
