"""Regenerate composite key in subscribers table

Revision ID: 078e7a7a27ef
Revises: 14f3afdc2c7e
Create Date: 2023-05-01 04:48:52.286738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078e7a7a27ef'
down_revision = '14f3afdc2c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.alter_column('subscriber_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('subscribee_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.alter_column('subscribee_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('subscriber_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
